### ISSUE TITLE
Auth Color & Room founder

### ISSUE THREAD

**Issue by zellman01** [PSservers15/OCPU#24]
The Auth color with the "/auth" is broken. Either we go back to the default auth list, or we somehow fix it.

Room founder currently does not exist for some reason.

**Comment by DeathlyPlays** [comment]
Is it using nameColor

**Comment by zellman01** [comment]
It doesn't look like it uses nameColor

**Comment by zellman01** [comment]
It probably used the color.js file

**Comment by DeathlyPlays** [comment]
Possibly or a nonexistent function
