### ISSUE TITLE
Custom Color

### ISSUE THREAD

**Issue by zellman01** [PSservers15/OCPU#46]
The Custom Colors will not be kept with new rooms created. How can be fixed without having to either apply new custom colors every time a new chatroom is created, or modifying the CSS?

**Comment by zellman01** [comment]
The easiest way to fix this is to reload the custom colors, but is there a way to have it auto-update without reloading custom colors?

**Comment by AlphaWind** [comment]
@zellman01 This should automatically be done by the plugin

**Comment by zellman01** [comment]
It does, but all of the clients would need to completely reconnect to see the changes. Is that quite literally the only way
