### ISSUE TITLE
Travis CI Build always failing

### ISSUE THREAD

**Issue by zellman01** [PSservers15/OCPU#7]
I need some massive help on trying to fix everything on the build. Right now there are over 500 errors, which most of them I don't really understand (then again, I'm only still a beginner for Node.js). It way too big of a list for me to put down here.

**Comment by zellman01** [comment]
Please use #11 for to fix all errors with the Travis CI build

**Comment by DeathlyPlays** [comment]
Ill fix it all

**Comment by zellman01** [comment]
Finally everything about the travis CI build is passed
